---
- name: lvmplaybook
  hosts: all
  tasks: 
  - name: create vg 
    lvg: 
      vg: vg1
      pvs: /dev/sde
  - name: create lv 
    lvol: 
      vg: vg1
      lv: lv1
      size: 2G
  - name: create filesystem
    filesystem: 
      fstype: xfs
      dev: /dev/vg1/lv1
  - name: create a directory
    file: 
      path: /lvdata
      state: directory
  - name: mounting directory
    mount:
      path: /lvdata
      src: /dev/vg1/lv1 
      fstype: xfs
      state: mounted
 
